export const BaseUrl = "http://localhost:5000"
export const RandPhotoUrl ="https://source.unsplash.com/random/1280x720/?life,lifestyle,HD,AI,food"
export const RandPhotoUrlChat ="https://source.unsplash.com/random/?walpaper,nature,background,dark"
export const SocketUrl = "http://localhost:5000"
// export const JwtSecret = "Whizchat@spsu"
